[package]
name = "noirc_driver"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noirc_errors = { path = "../noirc_errors" }
noirc_frontend = { path = "../noirc_frontend" }
noir_field = { path = "../noir_field" }
noirc_evaluator = { path = "../noirc_evaluator" }
noirc_abi = { path = "../noirc_abi" }
acvm = { path = "../acvm" }
std_lib = { path = "../std_lib" }
fm = { path = "../fm" }

dirs = "3.0"
pathdiff = "0.2"

[dev-dependencies]
ark-bn254 = { version = "^0.2.0", default-features = false, features = [ "curve" ] }
