[package]
name = "nargo"
version = "0.1.0"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
url = "2.2.0"
noirc_driver = {path = "../noirc_driver"}
noirc_frontend = {path = "../noirc_frontend"}
noir_field = {path = "../noir_field"}
noirc_abi = {path = "../noirc_abi"}
fm = {path = "../fm"}
acvm = {path = "../acvm"}

toml = "0.5"
serde_derive = "1.0.123"
serde = "1.0.123"
clap = "2.33.3"
termcolor = "1.1.2"
hex = "0.4.2"
ark-bn254 = { version = "^0.2.0", default-features = false, features = [ "curve" ] }
